In [30]:
# Linear Regression
import numpy as np

from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, Lasso
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

In [14]:
# Fitting a Line

# load data with only two features
boston = load_boston()
features = boston.data[:, 0:2]
target = boston.target

# create linear regression
regression = LinearRegression()
# fit the linear regression
model = regression.fit(features, target)

# view the intarcept
model.intercept_

22.485628113468223

In [15]:
# view feture coefficients
model.coef_

array([-0.35207832,  0.11610909])

In [16]:
# Predict the target value of the first observation, multiplied by 1000
model.predict(features)[0]*1000

24573.366631705547

In [20]:
# Handling Interactive Effects

# load data
boston = load_boston()
features = boston.data[:, :2]
target = boston.target

# create interaction term
interaction = PolynomialFeatures(degree=3,
                                include_bias=False,
                                interaction_only=True)
features_interaction = interaction.fit_transform(features)

# interaction_only gives us x1*x2 if it's True
# and x1^2< x2^2 and x1*x2 if it's not

# create linear regression
regression = LinearRegression()
# fit regression
model = regression.fit(features_interaction, target)

In [24]:
# Fitting a Nonlinear Relationship

# Load data with one feature
boston = load_boston()
features = boston.data[:,0:1]
target = boston.target

# create polynomial feature x^2 and x^3
polynomial = PolynomialFeatures(degree=3,
                                include_bias=False)
features_polynomial = polynomial.fit_transform(features)

# create linear regression
regression = LinearRegression()
# fit regression
model = regression.fit(features_polynomial, target)

In [28]:
# Reducing Variance with Regularization

# load data
boston = load_boston()
features = boston.data
target = boston.target

# Standardize features
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# create ridge regression with an alpha value (also called lambda)
regression = Ridge(alpha=0.5)
# fit the linear regression
model = regression.fit(features_standardized, target)


# tuning alpha coefficient using RidgeCV
regr_cv = RidgeCV(alphas=[0.1, 1, 10])
# fit regression
model_cv = regr_cv.fit(features_standardized, target)
# view coefficients
model_cv.coef_

array([-0.91987132,  1.06646104,  0.11738487,  0.68512693, -2.02901013,
        2.68275376,  0.01315848, -3.07733968,  2.59153764, -2.0105579 ,
       -2.05238455,  0.84884839, -3.73066646])

In [29]:
# view alpha (lambda)
model_cv.alpha_

1.0

In [31]:
# Reducing Features with Lasso Regression

# Load data
boston = load_boston()
features = boston.data
target = boston.target

# Standardize features
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# create lasso regression with alpha value
regression = Lasso(alpha=0.5)
# fit model
model = regression.fit(features_standardized, target)

# view coefficients
model.coef_
# it's intresting part of lasso regression that it shrinks some features out

array([-0.11526463,  0.        , -0.        ,  0.39707879, -0.        ,
        2.97425861, -0.        , -0.17056942, -0.        , -0.        ,
       -1.59844856,  0.54313871, -3.66614361])

In [32]:
# Create lasso regression with a high alpha
regression_a10 = Lasso(alpha=10)
model_a10 = regression_a10.fit(features_standardized, target)
model_a10.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])